classDiagram
    class Vista {
        + showUserLogin()
        + showUserData(User user)
        + showChildData(Child child)
        + showTapData(Tap tap)
    }

    class User {
        + int user_id
        + String username
        + String email
        + int rol_id
        + login()
        + logout()
    }

    class Child {
        + int child_id
        + String child_name
        + int sleep_average
        + int treatment_id
        + int time
        + getProgress()
    }

    class Tap {
        + int tap_id
        + int child_id
        + int status_id
        + Date init
        + Date end
        + updateTapStatus(status_id)
    }

    class Rol {
        + int rol_id
        + String type_rol
    }

    class Status {
        + int status_id
        + String name
    }

    class Treatment {
        + int treatment_id
        + String name
    }

    Vista --> User : displays
    Vista --> Child : displays
    Vista --> Tap : displays

    User --> Rol : has a
    Tap --> Status : has a
    Child --> Treatment : has a
