flowchart TD
    A[Cliente - Vista de login] --> B[Cliente - DAO]
    B --> C[Servidor - Webservice]
    C --> D[Servidor - DAO Usuaris]
    D --> E[Base de dades]
    E --> D
    D --> C
    C --> B
    B --> F[Cliente - Vista de l'infant]

