flowchart TD
    A[1 - Login] --> B{2 - Login OK?}
    B -- Sí --> C[3 - Pantalla Principal]
    B -- No --> D[4 - Error de Login]
    A --> E[5 - Registre]
    E --> F{6 - Registre OK?}
    F -- Sí --> C
    F -- No --> G[7 - Error de Registre]
    C --> H[8 - Perfil d'Usuari]
    C --> I[9 - Configuració]
    C --> J[10 - Tancar Sessió]
