sequenceDiagram
    participant User
    participant App
    participant WebService
   
    %% Intent de Inici de Sessió
    alt User Has Token
    User->>WebService: Token Login
    WebService->>BBDD: Request Login By Token
    BBDD->>Token: Check Login By Token

    else
    alt Regular Login
    User->>App: Credencials
    App->>WebService: Credencials
    end
    end
    WebService->>BBDD: Verifica Credencials
    alt Token 
    User-->>WebService: Request Token
    WebService-->>BBDD: Check Token
    BBDD-->>Token: Save Token
    end

    %% Token Recorrido
       alt Login OK
       Token-->>BBDD: Send Token
       end
   
    %% Inicialització correcte
        BBDD->>WebService: Login OK
        WebService->>App: Login OK
        App->>User: Login OK

    